### ISSUE TITLE
dark thème and french language

### ISSUE THREAD

**Issue by call5** [redsolution/xabber-android#425] opened 2015-05-08 14:36 UTC
I recently made an update in f-droid xabber of the version 0.9.30f towards the version 1.0.2, I like the work which was realized on the user interface, only I have some issues with the new version, I do not know if it is temporary and if that will be later corrected, I have not the application in French and I have not  the dark  theme in the application.

**Comment by aelmahmoudy** [comment] 2015-05-12 15:48
@call5 no dark theme in the new version (yet), I am working on a dark theme, not sure if Xabber devs are willing to accept it:
https://github.com/redsolution/xabber-android/pull/374

**Comment by grigoryfedorov** [comment] 2015-05-13 05:37
Translations would be added surely in stable version.
Dark theme also in plans, but priority is not that high.

**Comment by call5** [comment] 2015-05-13 15:50
@aelmahmoudy it's cool, I think a theme like this would be perfect, I hope the developers will integrate it in a future release. 

@grigoryfedorov okay so I will wait until the next stable release, but I can not see the current stable version in F-DROID

**Comment by andrewnenakhov** [comment] 2015-05-14 12:04
THis is mostly duplicate of #374

**Closed by andrewnenakhov** 2015-05-14 12:04 UTC
Labels: duplicate
