### ISSUE TITLE
Message carbons support

### ISSUE THREAD

**Issue by a-iv** [redsolution/xabber-android#128] opened 2013-02-05 09:03 UTC
http://xmpp.org/extensions/xep-0280.html

**Comment by dbanet** [comment] 2015-01-07 15:50
+1

**Comment by AnrDaemon** [comment] 2015-01-21 15:14
+1 long overdue
Especially considering zero effort beside adding one more enabler to authenticaton process.

**Comment by smoebody** [comment] 2015-04-21 16:12
switched to [conversations](https://play.google.com/store/apps/details?id=eu.siacs.conversations) now

**Comment by sponkydive** [comment] 2015-04-23 12:56
+1 please import. Conversations lacks in soo many other ways besides carbons

**Comment by bjo81** [comment] 2015-04-23 12:57
Yep. Conversations is quite annoying.

**Comment by smoebody** [comment] 2015-04-24 17:24
im very happy with conversations right now. cannot imagine what @sponkydive is missing or @bjo81 finds annoying. 
message carbons, otr, openpgp, chats, invitations, qrcodes, images, integrated look&feel, opensource ... its all there :)

but i dont want to advertise, just point out. everybody should decide for himself i guess.

**Comment by dbanet** [comment] 2015-04-24 17:32
@smoebody, groups! It's impossible to group contacts in Conversations. This is the main thing that prevents me from switching to Conversations. It is so essential, that I cannot believe it has not been implemented. Maybe there is something else I would be able to find, but without groups it is not usable for me, so I have stopped attempting to switch to it. Though, it's pretty beautiful, although I would prefer the dark theme, like the one in Xabber.

**Comment by andrewnenakhov** [comment] 2015-04-25 14:20
We are not really focused on XMPP improvements in Xabber at the moment, being busy with making Xabber look great and laying foundation for future features that are essential for Instant Messaging. 

btw we don't consider XEP280 to be essential, as it's not a good xep. It can't bring true device sync without relying on message archive XEPs and delivery control XEPs. So not a big priority for this one. Maybe eventually, since some servers do have support for it, and have nothing better than this.

**Comment by Bretos** [comment] 2015-04-25 14:33
During over 2 years, over 40 people (on GitHub at least) requested support for XEP-0280 only to finally find out that devs do not think it's "essential", even despite sent pullrequests implementing this feature.

Let's just hope for good (and quick) XEP-0313 integration then...

**Comment by andrewnenakhov** [comment] 2015-04-25 14:44
Well. XEP-313 is not too good either. You know, people seem to miss a point that device sync and message achive is the same task (one second after you've sent message it's already history!) and should not be solved separately. If we want good results, of course. 

But fear not. The whole point of resurrecting Xabber from it's dormant state is our mission to enable XMPP simple things that are offered by Telegrams, Vibers, WhatsApps etc - easy and reliable messaging, easy and reliable device sync, file transfer (and in-chat images, yes) + easy and user friendly security. XEP-280, 198, 313, 136 are not going to really help us achieve this goal. (But a good erlang developer would, btw)

**Comment by Bretos** [comment] 2015-04-25 14:48
So how do you plan to achieve this, given that XEPs you mentioned aren't going to help?

BTW. am I missing something, or does github repo not contain latest commits?

**Comment by dbanet** [comment] 2015-04-25 15:12
That's ridiculous. XEP-0136 already solves the history synchronization task. Just implement Carbons so that it syncs immediately. Gonna merge the pull request and build Xabber myself. I'm quitting this.

Sucks.

**Comment by andrewnenakhov** [comment] 2015-04-25 15:19
@dbanet, no, it does not. You'll know if you try (like we did). If it worked, any mobile and desktop XMPP client would sync and load history easily by now. But in reality XEP136 is considered deprecated, and XMPP is where it is. I'd even show you a vienn diagram with overlapping XEPs and their supposed functionality that we came to, but Github is a poor place for this.

@Bretos, as for achieving our goal, we plan to make our own extensions, and impement them on both client and server sides, of course.

**Comment by Bretos** [comment] 2015-04-25 15:20
So should we expect Xabber XMPP server soon? ;> 
or are you thinking about modules/extensions/patches for most popular ones?

**Comment by andrewnenakhov** [comment] 2015-04-25 15:24
We plan to start with ejabberd. It process one would accept our xeps, that'd be good, we'd be spared from additional work maintaining xabberd.

**Comment by bjo81** [comment] 2015-04-25 15:26
XEP-0313 works with gajim for example, no need to use carbons which spam the other clients.

**Comment by andrewnenakhov** [comment] 2015-04-25 15:31
@bjo81 Gajim rarely works with unreliable internet connection. XMPP had little issues on reliable networs. It's mobile devices with often faulty cellular coverage and frequent WiFi networks hopping (and re-establishing connection each time) that truly show XMPP weaknesses that we want to address.

(i think we should set up a forum or an email group for such discission)

**Comment by bjo81** [comment] 2015-04-25 15:46
Yep, but gajim is mostly used on devices with realiable connections, I think. Carbons are no good solutions, but XEP-0313 would be a big improvement IMHO.

**Comment by AnrDaemon** [comment] 2015-04-25 16:30
@andrewnenakhov, you're trying to make a point by dragging apart XEP's that intended to work TOGETHER.
Don't make mistake by saying "neither one of these will help", while they should be implemented BOTH to bring the desired results. That's why XEP-0136  has been deprecated in favor of TWO other - XEP-0280 Message Carbons and XEP-0313 Archive Support. You can't get the desired results without implementing both of them, you're not going to fool anyone here by saing that neither one of them will help. Of course implementing ONE will not help, you  need to implement both.
ejabberd supports XEP-0280(Carbons) but not XEP-0313(Archiving) - they have "P1-Spec" in their business version instead. Ref: https://www.process-one.net/en/ejabberd/protocols/

**Comment by bjo81** [comment] 2015-04-25 16:37
And prosody supports both, besides of some XEPs for unreliable connections.

**Comment by andrewnenakhov** [comment] 2015-04-25 16:48
@AnrDaemon those XEPs were never supposed to work together and, in fact, they never do (prove me wrong by pointing to successful implementation!) - and you also forgot to throw in XEP-0198 to ensure message delivery, since supporting Archive and Carbons without delivery control is pointless (and don't get me started now on cases where 198 does not ensure delivery!). Those XEPs were all developed independently to achieve some narrow goals of their authors, and you suggest trying to glue them together when they are simply not designed for the task.

You see, I don't oppose idea of implementing all these XEPs in #Xabber. I just know that they wouldn't really work in 100% cases - merely in 90% or so (and you should trust me, since I'm the guy who pays for Xabber development), so I see no sense wasting resources on these things instead of really solving a problem (not a really hard one - #telegram developers figured it out from the first try!).

**Comment by AnrDaemon** [comment] 2015-04-25 17:22
Okay, you found flaws in currently proposed standards. Point them! Propose corrections!
Don't just say "I know this will never work!" Of course it will never work, if nothing is done about it.

**Comment by andrewnenakhov** [comment] 2015-04-25 17:26
Well that's the plan, but we'd rather back our words with successful
implementation, not just theory.
25 апр. 2015 г. 22:22 пользователь "AnrDaemon" <notifications@github.com>
написал:

**Comment by OverkillTASF** [comment] 2015-04-25 20:46
Andrew, thanks for posting in here. You could have just ignored the thread, and instead you popped in, shared some status and plan info, and accepted some of the complaints from posters. I too am a free-loader who can't offer any help in making Xabber more of what I want. I thank you for your work and look forward to seeing if the plan comes to fruition.

**Comment by AnrDaemon** [comment] 2015-04-25 20:59
@andrewnenakhov, while you are still working out your implementation, which may take another year or so, you could at least raise your concerns over at the http://xmpp.org/ so people would be aware of them.

**Comment by moshpirit** [comment] 2015-05-09 10:59
I think that Conversations has done an excellent work with Carbons and MAM. Xabber should do probably the same IMO.

**Comment by weiss** [comment] 2015-05-13 20:29
> Those XEPs were all developed independently to achieve some narrow goals of their authors, and you suggest trying to glue them together [...].

Welcome to XMPP :-)

Seriously, that's the downside of using an open standard that's easily extensible.  A single vendor that builds a custom product from scratch (you mentioned Telegram) can easily provide a consistent solution, but with the obvious downside of having no interoperability with existing implementations.

I agree the goal you're trying to achieve is "proper device synchronization", and this task could indeed be simplified by replacing the existing extensions with a new one (just as everything could be *greatly* simplified by re-doing XMPP from scratch).  But the extensions in question are implemented in various places already (@AnrDaemon, ejabberd also [supports XEP-0313][mod_mam]), and that's a very good reason not to add yet another XEP to the mess.

> those XEPs were never supposed to work together

Maybe not initially, but there's on-going work on these XEPs, explicitly driven by the idea of combining them in order to achive proper device synchronization, based on implementation experience.

> I just know that they wouldn't really work in 100% cases - merely in 90% or so

I'd be interested in what cases you have in mind.  One issue I see is that it's currently hard to avoid duplicates when live messages are sent or received while the MAM archive is queried.  That's going to be solved by having the server tag all messages with UUIDs.  Are there other problems you see?

> I'd even show you a vienn diagram with overlapping XEPs

Aren't you currently suggesting to add another XEP with overlapping functionality?

[mod_mam]: https://github.com/processone/ejabberd-contrib/tree/master/mod_mam

**Comment by vladimmi** [comment] 2015-09-20 11:32
Issue opened for almost 3 years, most of servers implement listed XEPs (to list some - Tigase, ejabberd, Prosody, Openfire), many clients support and use this but Xabber authors keep saying it's bad and users do not need it...

**Comment by Bretos** [comment] 2015-09-20 11:35
PR implementing XEP-0280 has been merged, and message carbons is supported at least by latest F-Droid [release](https://f-droid.org/repository/browse/?fdid=com.xabber.androiddev)

**Comment by vladimmi** [comment] 2015-09-20 11:37
@Bretos Thanks, need to try out - Play Market one (Xabber, not a Xabber beta) doesn't seem to have it

**Comment by moshpirit** [comment] 2015-09-20 11:38
It's also one of the first XEPs implemented on Conversations, but these are different clients and different developers who use their time and effort to improve their projects for free. What I think that Xabber needs is MAM to improve Carbons but that's another thing.

**Comment by andrewnenakhov** [comment] 2015-09-21 11:37
@vladimmi you may always do a fork of Xabber and implement all features and XEPs you want and need, or send us a correctly working PR with XEP-0280 (that mentioned one has issues), we'll merge it into main version. In the meantime we are working on features that we consider more important than supporting some XEPs that we consider lame. I understand that you want device sync, but message carbons aren't meant for that. So even having that XEP implemented you won't get what you want, it'll get you only deliver what it does - 'message carbons'. That's why we don't waste our time on this one.

**Comment by AnrDaemon** [comment] 2015-09-22 12:56
Again?... Stop pointing to one XEP in separation and telling that "it won't solve the problem".
Of course it would not. It would solve part of it, and there's other XEP's that solve other parts.
You need them all implemented to solve problem as a whole.

**Comment by andrewnenakhov** [comment] 2015-09-22 13:10
This approach is exac reason that led us to current situation with very poor mobile xmpp experience. Users want good and reliable device sync, not a poor solution loosely sewed together from various methods that were offered for very different reasons. If you'd try to really look into these XEPs yourself and try to implement them you'd see MANY problems that are conseqences of this approach. These XEPs aren't designed to do device sync and that's why they don't do it well. MAM alone is much more important for sync than carbon copies, but it lacks some features to do it really well. 

What SHOULD really work for device sync is a XEP designed for this specific task. We'll work on it a bit later when we have free resources to do so.

**Comment by vladimmi** [comment] 2015-09-22 13:43
@andrewnenakhov, while I really appreciate your work on Xabber so it is maybe the best looking and user friendly while fast XMPP client on Android, I cant understand your point for a current feature lack and unwillingness to change something to improve that.

You say `send us a correctly working PR [...], we'll merge it into main version` but it took a YEAR to merge #299 - according to comments, 4 monthes just to look at it, then 7 monthes more to merge it into dev branch. How can users send PRs when they left opened for so long time? And dont know what issues you are talking about, PR comments contain only formatting problems.

And the last one - what do *you* exactly mean by "device sync"? Personally me just need to have message sent from one client to appear in another online one (like "sent from desktop, shown on online mobile too") to switch between them and incoming messages shown on all online clients (like "someone sent message to a mobile resource, it's shown on online desktop too") - and that's what carbons exactly do, no? I dont need any history sync (hystory is turned off) - just live-sharing messages between online devices to not miss when some client send message to full JID of device left online at home, for example.

**Comment by weiss** [comment] 2015-09-22 15:36
> If you'd try to really look into these XEPs yourself and try to implement them you'd see MANY problems that are conseqences of this approach.

I'd [still][1] be interested in a single example of such a problem, especially one that's not fixable by applying simple updates to those XEPs.

[1]: https://github.com/redsolution/xabber-android/issues/128#issuecomment-101806083

**Comment by andrewnenakhov** [comment] 2015-09-22 19:29
@weiss easily. Standard XMPP in poor connectivity conditions is, to say, poor. Server and client are not properly informed on message delivery, that leads to duplicating messages (there are quite dirty and not 100% reliable hacks in Xabber to combat this issue!). If you throw carbon copies, MAM in the mix, you'll often find yourself choosing whether message in archive is a copy of message you received carbon copy, or just another message with same text. Someone recently understood this as well as we, it resulted in XEP-0359, that could mitigate problems. So, to offer something that Telegram does easily both client and server must support XEPs 280, 313, 198 and now 359. And what do you know, even all this won't be enough, because there are cases when XEP-0198 still might lose stanzas. Anyway, EVERY server and EVERY client should support a number of XEPs, solve issues with their incomplete coherence with each other, and only then mobile experience would be 'so-so'. 

In order to REALLY move xmpp forward on mobile we need to create a simple and reliable way to do what users want us to do - MESSAGE SYNC BETWEEN DEVICES! Replace all this mess with a GOOD solution. 

Btw, what @vladimmi says clearly demonstrates some faults in XMPP approach as a whole - to our experience all this priorities system in XMPP is only usable by geeks like us, not users who want all their chats on all their devices.

**Comment by andrewnenakhov** [comment] 2015-09-22 19:41
@weiss sorry, I have read your earlier post from May, 14 only now. Should have written my previous post a bit differently - you've correctly pointed to message duplicating. What you don't know is how much pain did we have with this issue in early versions Xabber. We've also implemented XEP-0198 in our other project and we know for sure that it's not 100% reliable. 

@vladimmi as for pull requests taking 1 year to merge, that's quite simple - we didn't have a free developer to work on this, and all available time was spent on rebuilding Xabber interface - it was obsolete and was really holding us back. Some $2000/month would more than double pace of Xabber development. :)

**Comment by dbanet** [comment] 2015-09-22 20:38
![xkcd on standarts](https://imgs.xkcd.com/comics/standards.png)

Kill it with fire.

**Comment by andrewnenakhov** [comment] 2015-09-22 20:47
This classic xkcd is not exactly relevant here. Competing 'standards' are
Telegram, WhatsApp, Viber, Facebook Messenger, Hangouts, WeChat, Tango,
Line and myriad others, and each and every of them are currently _better_
than XMPP in this regard.
23 сент. 2015 г. 1:38 пользователь "dbanet" <notifications@github.com>
написал:

**Comment by dbanet** [comment] 2015-09-22 21:03
I didn't use anything from this list but WhatsApp, which is awful regarding connecting with multiple clients at once. Really, they have solved it by restricting this: you *can* chat from a PC, but that actually uses your phone, so when it disconnects, you disconnect from the PC either.

Apart of this issue, everything from this list is actually far more worse than XMPP.

I have two desktop XMPP clients (Vacuum IM forks) synchronizing perfectly: carbons are on and the history is stored on the server.

The comic applies.
You have been talking about your standard for two years with *no* fucking outcome.
You have no resources. How is thinking about competing even sane?

**Comment by OverkillTASF** [comment] 2015-09-22 21:06
DBANet, please remember that development on Xabber is largely voluntary;
Pretty sure no one is making a healthy income on it. Your tone smacks of
entitlement and detracts from any of the good points you were trying to
make.

**Comment by dbanet** [comment] 2015-09-22 21:10
>DBANet, please remember that development on Xabber is largely voluntary; Pretty sure no one is making a healthy income on it. Your tone smacks of entitlement and detracts from any of the good points you were trying to make.

oVerKILltaSF, I don't care.

**Comment by moshpirit** [comment] 2015-09-22 21:12
Well, actually you can use web.WhatsApp.com or something like that, it's an official web client. Anyway, it will always be Whatsucks for me.

About the XKCD comic... The point of XMPP is that you can use the app that you prefer will all of the accounts that you want hosted in the servers that you want :-)

Please, don't reply this answer, I don't want to create an offtopic chat here.

**Comment by dbanet** [comment] 2015-09-22 21:14
>Well, actually you can use web.WhatsApp.com or something like that, it's an official web client.

That's what I'm talking about.
It requires your mobile phone to be online.

**Comment by weiss** [comment] 2015-09-22 21:14
>  you've correctly pointed to message duplicating. What you don't know is how much pain did we have with this issue in early versions Xabber.

Indeed, that's why I asked.  My question wasn't rhetorical.

For incoming messages, the issue was already solved in MAM 0.2 by [injecting the MAM UID into live messages][1].  This feature is [removed][2] in MAM 0.3/0.4, but it's supposed to come back, together with a solution for outgoing messages (sent from your client or from other devices).

> We've also implemented XEP-0198 in our other project and we know for sure that it's not 100% reliable.

As I've implemented this for ejabberd, I'd be interested in details.  While the stanza counting is too error-prone for my taste, you *can* get that right, and then I don't see reliability issues.

>  to offer something that Telegram does easily both client and server must support XEPs 280, 313, 198 and now 359.

Well, XEP-0198 is mostly just an optimization if you implemented the other XEPs.  And XEP-0359 was splitted off just to make it reusable, this separation doesn't add complexity.  So I think we're really just talking about XEP-0280 vs. XEP-0313.  It has indeed been [suggested][3] to unify both by having the MAM service also take care of Carbons (I've implemented that [for ejabberd][4]). But I don't think this makes that much of a difference for client developers.

> Replace all this mess with a GOOD solution.

I'm all for simplicity, but I'm also all for avoiding redundant XEPs.  XMPP has way too many of those already, and this is problematic for pushing XMPP forward as well.

[1]: http://xmpp.org/extensions/attic/xep-0313-0.2.html#sect-idp616432
[2]: http://mail.jabber.org/pipermail/standards/2015-January/029528.html
[3]: http://geekplace.eu/xeps/xep-mamsub/xep-mamsub.html
[4]: https://github.com/weiss/ejabberd-contrib/commit/f8a85b1c5ced81723d111f0ef5463942589f837d

**Comment by dbanet** [comment] 2015-09-22 21:16
>I'm all for simplicity, but I'm also all for avoiding redundant XEPs. XMPP has way too many of those already, and this is problematic for pushing XMPP forward as well.

Agreed wholeheartedly.

**Comment by OverkillTASF** [comment] 2015-09-22 21:18
Andrew, given the current XEP's out there, are you saying that none of
them, if properly implemented on servers and clients, would create an
environment where multiple clients can be kept in sync, or even /mostly/
in sync?

If all of those XEP's are a huge amount of work but would only allow for
half of the messages being relayed, obviously probably not worth it. But
if it's a marginal amount of work that would get most messages synched
with just a few exceptions, that could still be worth it even if not
perfect.

If not this sync across clients in poorly connected environments, what
would you say is the priority of the XMPP development (Not just Xabber)
community right now? What new sexy things are XEP's being added for?

-----

**Comment by andrewnenakhov** [comment] 2015-09-22 21:48
Telegram currently is better for users than XMPP in every possible way. It
has a brilliant app, and a very good protocol *designed* to work on
multiple devices of different types. It's only fault is that it's not
federated (could be fixed too, btw).

As for perfect synchronized xmpp clients, I say this: "Ha-ha" and this:
"ha-ha-ha". Desktop is not mobile, XMPP faults are undetectable on stable
connection (probably that's why they weren't addressed 15 years ago!). XMPP
lost momentum the exact moment smartphone revolution happened, losing all
grounds to Tango/WhatsApp/Viber/etc - not because of those services
advantages, but more due to its own faults.

Biggest fault is not even inconsistent XEPs, it's TCP! But rewriting from
scratch we'll end up with something like Telegram's protocol.

Anyway, XMPP was designed as an open alternative to ICQ, and now we need
alternative to Facebook Messenger and the rest from that list, but XMPP is
not designed for it. Idea behind it is decades old and is good enough for
desktop PCs, but the world has moved on, and that's why XMPP needs to be
adapted to today's challenges and users needs.

As for 'fucking outcome', we currently lack experienced erlang developer.
And time, of course.

Btw, its not wise to trash apps as 'far more worse than XMPP' - if you
aren't seeing their value for users it's only your perspective on things.
Those apps are used instead of Xabber or Conversations or Pidgin because of
simplicity, convenience, reliability, network effect. Try telling some
random non-geek person about priorities and full jids, ha.

I didn't use anything from this list but WhatsApp, which is awful regarding
connecting with multiple clients at once. Really, they have solved it by
restricting this: you *can* chat from a PC, but that actually uses your
phone, so when it disconnects, you disconnect from the PC either.

Apart of this issue, everything from this list is actually far more worse
than XMPP.

I have two desktop XMPP clients (Vacuum IM forks) synchronizing perfectly:
carbons are on and the history is stored on the server.

The comic applies.
You have been talking about your standard for two years with *no* fucking
outcome.
You have no resources. How is thinking about competing even sane?

—
Reply to this email directly or view it on GitHub
<https://github.com/redsolution/xabber-android/issues/128#issuecomment-142421064>
.

**Comment by andrewnenakhov** [comment] 2015-09-22 22:16
@OverkillTASF priorities for XMPP community should be:
 - simplicity - no redundant and interdependent XEPs for mundane tasks
 - ease of development 
 - something like voluntary certification program from xmpp.org and some testing process to check compliance to standards and essential XEPs. This table alone http://jabberworld.info/Jingle stops me from even thinking on implementing jingle in Xabber.

**Comment by AnrDaemon** [comment] 2015-09-23 11:18
Redundancy is what you will achieve, if you remove dependency. Though, I hope that "inter-" was the key in your statement. Standards that rely one on another to do basic functionality together is really not what brings robustness to the end product.
But… With all due respect, what you so far was suggesting is to tear down the foundation and rebuild from scratch.
Something like this was attempted some 98 years ago. Remember, in 1917? How well it worked out? And what makes you think that it would work better today?
What XMPP is lacking is message identification, as you demonstrated recently. And which is quite easy to observe, too.
However, the [XEP-0359](https://xmpp.org/extensions/xep-0359.html) is partial at best. It only provide a way to uniquely identify the message, but does not help to preserve its metadata.

**Comment by andrewnenakhov** [comment] 2015-09-23 11:57
No, @AnrDaemon , I don't agree. In theory what you say sounds plausible. But you know the difference between theory and practice? In theory, there is no difference. However, think of this from a developer perspective. In order to support some basic functionality not only we have to implement all these interdependent XEPs, but we have to be sure that server that'll work with our client will support all these XEPs too, and do it without errors (there are MANY issues with implementation of each of these XEPs on various servers, trust me). If, say, server does not support for MAM, what we'll hear from our users? "Bah, this Xabber loses messages, I didn't receive all that was sent to me, booo!" We'd rather detect if server supports this purposed 'Device sync' XEP, if server supports 'Reliable delivery XEP', and be done with it - we'll be sure it'll work correctly for our purposes. 

It's hard for us to make this quite basic feature done right with all these XEPs loosely glued together, and it's hard for any other developer as well. 

Reasoning behind extensions should be simplicity: If you want to do something, do one thing, but do it right. Using 0280, 0313, 0198 and 0359 for device sync is not easy and not right. What surprises me most is that issue at hand is quite simple and obvious, solved easily by many other protocols and developers, and only XMPP lags behind. I can't explain it with anything but this messy state of interdependency on XEPs what were all meant for something else.

**Comment by moshpirit** [comment] 2015-09-24 04:53
That solution sounds great, thank you!! But if it's not so different from the actual MAM, could you start implementing the XEP for these users that we know that our servers allow MAM? (I ask you from absolute ignorance)

**Comment by andrewnenakhov** [comment] 2017-05-25 14:20
Anyway support for carbons was added to Xabber 2.0, but we're not finished with things we've discussed here.

**Closed by andrewnenakhov** 2017-05-25 14:20 UTC
Labels: enhancement
