### ISSUE TITLE
Block messages from users not in my contact list

### ISSUE THREAD

**Issue by readyblue** [redsolution/xabber-android#673] opened 2016-12-15 11:37 UTC
Can you please add simple block from users not in my contact list?
I receive 3-4 random spams every day when on xabber.

**Comment by mis2417** [comment] 2016-12-26 16:07
yes!  privacy lists are really, really needed. please.

**Comment by mis2417** [comment] 2017-02-03 12:40
#615 is a duplicate

**Comment by climf** [comment] 2017-03-01 00:00
xep-0016 is a true joy

**Comment by andrewnenakhov** [comment] 2017-05-25 17:25
Duplicate of #21

**Closed by andrewnenakhov** 2017-05-25 17:25 UTC
