### ISSUE TITLE
Add WhatsApp support

### ISSUE THREAD

**Issue by deniss-s** [redsolution/xabber-android#353] opened 2015-02-10 22:05 UTC
WhatsApp is XMPP based, is it possible to add support for WhatsApp contacts (phone_number@s.whatsapp.net)?

**Comment by deanet** [comment] 2015-02-11 03:15
+1

**Comment by andrewnenakhov** [comment] 2015-02-13 13:46
This is duplicate of #238 

We do not currently plan to support closed platforms, so there will be no implementation of WhatsApp unless WhatsApp will support open XMPP gateway. 

Anyway, considering recent WhatsApp actions to ban third-party apps and block users using them ( http://techcrunch.com/2015/01/21/whatsapp-cracks-down-on-third-party-apps-temporarily-bans-their-users-from-its-service/ ), there is really no point trying to make this issue work.

**Closed by andrewnenakhov** 2015-02-13 13:46 UTC
