### ISSUE TITLE
Missing some messages in MUC history

### ISSUE THREAD

**Issue by wrooot** [redsolution/xabber-android#709] opened 2017-04-18 04:09 UTC
Using 2.0.1. When i connect to open_chat room at conference.igniterealtime.org, Xabber doesn't show some of the messages. It's like it has gaps at some intervals. Misses 2 messages, then shows everything (10-15 messages), then again misses a few. Comparing to Conversations, Spark (which show everything).

**Comment by Artiom-M** [comment] 2017-09-25 13:52
The same issue. Even with stable 2.0.2 from GooglePlay. Other clients shows everything

**Comment by andrewnenakhov** [comment] 2017-09-25 14:09
We cannot reproduce this issue on our servers. @Artiom-M @wrooot can you give us account on your servers so we can see what's going on there?

**Comment by wrooot** [comment] 2017-09-25 16:55
How can i share the test account credentials?

**Comment by andrewnenakhov** [comment] 2017-09-25 17:39
@wrooot email them info@xabber.com - and please provide details how to access affected conference (say how it is named). We'll try to look at it this week then.

**Comment by wrooot** [comment] 2017-09-25 17:49
Sent. I haven't tried Xabber for a while, but as Artiom mentions it, maybe this issue is still there.

**Comment by andrewnenakhov** [comment] 2017-09-25 18:19
@wrooot I don't see incoming email with credentials there... re-send please.

**Comment by wrooot** [comment] 2017-09-25 18:35
Resent. Though i saw test in the chat. Thought maybe it was you.

**Comment by Artiom-M** [comment] 2017-09-25 18:54
Additional info: the same conference works well with Xabber 1.0.74

**Comment by andrewnenakhov** [comment] 2017-09-27 08:24
@wrooot it wasn't us yet, developer is currently ill :(

**Comment by andrewnenakhov** [comment] 2019-01-12 14:48
Closing, since we're going to replace MUC protocol with new superior group chat protocol.

**Closed by andrewnenakhov** 2019-01-12 14:48 UTC
Labels: bug
