### ISSUE TITLE
Add a default muc server per account

### ISSUE THREAD

**Issue by guest20** [redsolution/xabber-android#526] opened 2015-08-11 06:57 UTC
I usr Xabber for corporate Jabber and am often bouncing between mucs. Typing "conference.Jabber.example.com" each time I join a 3 or 4 letter muc is a lot of overhead.

It would be nice to be able to set a default. I'm not sure how the ui works with more than one account, but I would assume it would make sense to change the server when you pick another identity.

**Comment by andrewnenakhov** [comment] 2017-05-25 18:45
Duplicate of #58 , implementing last server name should help

**Closed by andrewnenakhov** 2017-05-25 18:45 UTC
