### ISSUE TITLE
F-Droid automatic builds failing since 1.0.168

### ISSUE THREAD

**Issue by RandDruid** [redsolution/xabber-android#711] opened 2017-04-18 14:55 UTC
Any chance to fix this issue?
-------------------------------------------------------------
Build log (from F-Droid site):

== Installed Android Tools ==

* android-compatibility (19)
* build-tools/18.0.1 (18.0.1)
* build-tools/19.0.0 (19)
* build-tools/android-6.0 (23.0.3)
* platform-tools (24 rc2)
* platforms/android-14 (3)
* platforms/android-23 (1)
* platforms/android-5 (1)
* platforms/android-9 (2)
* tools (24.4.1)
INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
INFO: Building version 2.0.1 (348) of com.xabber.androiddev
INFO: Getting source for revision 2.0.1
INFO: Initialising submodules
INFO: Creating local.properties file at build/com.xabber.androiddev/local.properties
INFO: Creating local.properties file at build/com.xabber.androiddev/xabber/local.properties
INFO: Cleaning Gradle project...
INFO: Scanning source for common problems...
ERROR: Found unknown maven repo 'https://igniterealtime.org/repo' at build.gradle
WARNING: Found JAR file at gradle/wrapper/gradle-wrapper.jar
ERROR: Could not build app com.xabber.androiddev: Can't build due to 1 errors while scanning

**Comment by relan** [comment] 2017-04-18 18:44
1b06ac0cbf3bd09b3b770dda47843a7ed6d60c19 introduced Smack snapshots from https://igniterealtime.org/repo. This repository is not known to F-Droid, thus the build failed.

**Comment by yourealwaysbe** [comment] 2017-04-24 09:59
I have a merge request in F-Droid with a workaround [here](https://gitlab.com/fdroid/fdroiddata/merge_requests/2191).  It replaces the cutting-edge version (4.2.1+) of Smack with the most recent release on Maven Central (4.2.0).  The question is, is 4.2.0 good enough, or is there a specific reason Xabber uses the newer versions?

**Comment by casperklein** [comment] 2017-04-24 11:21
I can't answer that question. But IMHO to avoid problems in the future, the versions should be the same.
If I remember correctly, there were some bugs in smack relevant to Xabber, that where fixed in the snapshot.

**Comment by aelmahmoudy** [comment] 2017-04-26 01:04
@grigoryfederov can you comment ?

**Comment by cl0ne** [comment] 2017-04-28 18:36
Any news on issue? As far as I understand it is the reason why on GooglePlay latest version but not on F-Droid, right?

**Comment by matthewhague** [comment] 2017-05-18 10:29
2.0.1 should appear on fdroid now -- built with the correct version of Smack.

**Comment by yourealwaysbe** [comment] 2017-05-18 10:29
2.0.1 should appear on fdroid now, built with the correct version of Smack.

**Comment by cl0ne** [comment] 2017-05-18 14:49
@yourealwaysbe Confirmed, built on 15.05

**Closed** 2017-05-26 09:02 UTC
