### ISSUE TITLE
Can't connect to Jabberd 2.2.11-4.el5

### ISSUE THREAD

**Issue by slaveniamh** [redsolution/xabber-android#284] opened 2014-02-10 18:42 UTC
The server log shows-

jabberd/c2s packet sent before session start

Any ideas?

Niamh

**Comment by andrewnenakhov** [comment] 2015-01-30 15:59
Need more data.

**Comment by iNPUTmice** [comment] 2015-04-27 11:01
duplicate of #396

**Closed** 2015-05-14 13:19 UTC
Labels: question
