### ISSUE TITLE
SPAM / Msgs from roster contacts only

### ISSUE THREAD

**Issue by xeverse** [redsolution/xabber-android#615] opened 2016-02-25 14:49 UTC
Considering the spammers activity has been on the rise.
This is the only spam prevention measue that i can think of.

Is there a possiblilty on the xmpp protocol level for that
or should this kind of filtering better be implemented in client?

**Comment by krushmp** [comment] 2016-09-16 07:50
XEP 0016, Privacy Lists

**Comment by climf** [comment] 2017-03-01 00:00
yes.  it is xep-0016

**Comment by petrpulc** [comment] 2017-03-04 11:26
@climf well, not necessarily.
a) many severs do not support full xep-0016
b) blocking on client is sometimes a better solution

**Comment by andrewnenakhov** [comment] 2017-05-25 17:25
Duplicate of #21

**Closed by andrewnenakhov** 2017-05-25 17:25 UTC
Labels: duplicate
