### ISSUE TITLE
Xabber spams connection / disconnection messages

### ISSUE THREAD

**Issue by Bugsbane** [redsolution/xabber-android#200] opened 2013-05-10 20:00 UTC
Hi there,

Not sure if it's just a message sending issue or an actual network disconnection issue, however, my wife uses Xabber, and frequently (and pretty much any time she logs in our out), I get sent about 50 messages, all within one second basically repeating variations of:

15:45:21 xxx@yyy.zz has become Available
15:45:21 xxx@yyy.zz has become Offline

Often they alternate. Sometimes there's 50 "is available" messages in a row. Occasionally there's an "Extended away" message in there, too. I guarantee you, she's not manually logging off and on 50 times a second. :)

She's on a Samsung Galaxy Tab (first edition) with Gingerbread (2.3).

Sometimes this happens so often, it's hard to find the actual legitimate messages inside literally hundreds of these connection messages. If often seems to happen just before she gets disconnected, so I'm not sure if this is causing a disconnection, or just a reaction to it.
![xabber](https://f.cloud.github.com/assets/401733/489980/32a54cf0-b9ac-11e2-901c-d17352d0da3d.png)

**Comment by andrewnenakhov** [comment] 2015-02-03 15:27
Can anyone confirm / reproduce this issue?

**Comment by Bugsbane** [comment] 2015-02-05 02:29
Holy cow. Not even I could any more. I don't have that tablet anymore. I don't use Windows any more. I don't have that wife any more. And I'm not using Xabber any more.

In response to a previous comment, we were using one of the Jabber servers mentioned on Jabber.org. I think it may have been a jabber.org account.

**Comment by andrewnenakhov** [comment] 2015-02-05 15:49
Well, since we can't reproduce this issue, i'm closing it. Good luck with new wife! :)

**Closed by andrewnenakhov** 2015-02-05 15:49 UTC
Labels: bug

**Comment by Bugsbane** [comment] 2015-02-07 09:29
Thanks. Hoping wife v2.0 proves to be a more stable release...
