### ISSUE TITLE
Support for SDK26

### ISSUE THREAD

**Issue by NextGenDevIndia** [redsolution/xabber-android#796] opened 2018-02-01 03:52 UTC
Any plan for support of compile sdk version 26 ?
We tried to compile it is giving DNS error on port 5222.

**Comment by oxoWrk** [comment] 2018-02-01 04:24
what is the relationship between sdk  version and DNS error ?
what is the relationship between DNS and port 5222 ?

**Comment by Str4tocaster** [comment] 2018-02-01 04:25
You can compile and run application or not? Are you have this error on compile time or runtime?

**Comment by NextGenDevIndia** [comment] 2018-02-02 04:35
We are able to compile and run, but on socket connection, it is throwing DNS error.
Getting below error

ExtendedResolver: got java.net.PortUnreachableException
com.mymessage.managers.DNSManager@900bbaa: Update address for <host>
com.mymessage.managers.DNSManager@900bbaa: Update address for <host>
com.mymessage.connection.ConnectionThread@27898cd
W/System.err: There is no available address.: 
W/System.err:     at com.mymessage.connection.ConnectionThread.onAddressResolved(ConnectionThread.java:252)
W/System.err:     at com.mymessage.connection.ConnectionThread.onAddressResolved(ConnectionThread.java:231)
W/System.err:     at com.mymessage.connection.ConnectionThread.access$200(ConnectionThread.java:40)
W/System.err:     at com.mymessage.connection.ConnectionThread$5.run(ConnectionThread.java:207)
W/System.err:     at com.mymessage.connection.ConnectionThread$21.run(ConnectionThread.java:664)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by NextGenDevIndia** [comment] 2018-02-16 06:42
is any one facing same issue ?

**Comment by Str4tocaster** [comment] 2018-03-28 11:30
@NextGenDevIndia The problem is Android Oreo changed method of getting DNS-servers. Now it fixed in https://github.com/redsolution/xabber-android/commit/caf36e4ff97718e5054696dac4373381af9bbeeb. We also support SDK 27 now

**Closed by Str4tocaster** 2018-03-28 11:30 UTC
